var Vue = require('vue')
var VueRouter = require('vue-router')

Vue.use(VueRouter)

export default new VueRouter({
  mode: 'history',
  scrollBehavior: () => ({y: 0}),
  routes: [
    { path: '*', component: resolve => require(['./components/err404'], resolve) },
    { path: '/',                redirect: '/login' },
    { path: '/error404',        component: resolve => require(['./components/err404'], resolve) },
    { path: '/error401',        component: resolve => require(['./components/err401'], resolve) },
    { path: '/error',           component: resolve => require(['./components/errpage'], resolve) },
    { path: '/login',           component: resolve => require(['./views/login'], resolve) },
    { path: '/loginNca',           component: resolve => require(['./views/loginNca'], resolve) },
    { path: '/loginErc',           component: resolve => require(['./views/loginErc'], resolve) },
    { path: '/NCASaleOutInvoiceControl',     component: resolve => require(['./views/nca/inventorymanage/NCASaleOutInvoiceControl'], resolve) },
    { path: '/NCAMaterialInvoiceControl',     component: resolve => require(['./views/nca/ordermanage/NCAOrderDetailControl/NCAMaterialInvoiceControl.vue'], resolve) },
    { path: '/common/baseconfig',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'FollowerControl',             component: resolve => require(['./views/common/baseconfig/FollowerControl'], resolve) }
    ]},
    { path: '/common/system',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'SystemApiControl',             component: resolve => require(['./views/common/system/SystemApiControl'], resolve) },
            { path: 'DomainTemplateControl',        component: resolve => require(['./views/common/system/DomainTemplateControl'], resolve) },
            { path: 'DomainControl',                component: resolve => require(['./views/common/system/DomainControl'], resolve) },
            { path: 'DomainGroupControl',           component: resolve => require(['./views/common/system/DomainGroupControl'], resolve) },
            { path: 'OperatorControl',              component: resolve => require(['./views/common/system/OperatorControl'], resolve) },
            { path: 'SysGroupApiControl',           component: resolve => require(['./views/common/system/SysGroupApiControl'], resolve) },
            { path: 'UserSetting',                  component: resolve => require(['./views/common/system/UserSetting'], resolve) },
            { path: 'ResetPassword',                component: resolve => require(['./views/common/system/ResetPassword'], resolve) }
    ]},
    { path: '/nca/customermanage',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'NCACustomerControl',           component: resolve => require(['./views/nca/customermanage/NCACustomerControl'], resolve) },
            { path: 'NCACustomerDetailControl',     component: resolve => require(['./views/nca/customermanage/NCACustomerDetailControl'], resolve) },
            { path: 'NCAAppointmentControl',        component: resolve => require(['./views/nca/customermanage/NCAAppointmentControl'], resolve) },
            { path: 'NCAInquiryControl',            component: resolve => require(['./views/nca/customermanage/NCAInquiryControl.vue'], resolve) },
            { path: 'NCACustomerAssignControl',     component: resolve => require(['./views/nca/customermanage/NCACustomerAssignControl.vue'], resolve) },
            { path: 'NCACustomerAssignDetailControl',   component: resolve => require(['./views/nca/customermanage/NCACustomerAssignDetailControl.vue'], resolve) },
            { path: 'NCAComplaintControl',              component: resolve => require(['./views/nca/customermanage/NCAComplaintControl'], resolve) },
            { path: 'NCAUserComplaintControl',              component: resolve => require(['./views/nca/customermanage/NCAUserComplaintControl'], resolve) },
            { path: 'NCALoanControl',      component: resolve => require(['./views/nca/customermanage/NCALoanControl'], resolve) }
        ]},
    { path: '/nca/NCAOrderSearchControl',     component: resolve => require(['./views/nca/ordermanage/NCAOrderSearchControl'], resolve) },
    { path: '/nca/ordermanage',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'NCAOrderControl',              component: resolve => require(['./views/nca/ordermanage/NCAOrderControl'], resolve) },
            { path: 'NCALandAgentOrderControl',     component: resolve => require(['./views/nca/ordermanage/NCALandAgentOrderControl'], resolve) },
            { path: 'NCAOrderDetailControl',        component: resolve => require(['./views/nca/ordermanage/NCAOrderDetailControl/NCAOrderDetailControl.vue'], resolve) },
            { path: 'NCAGOrderDetailControl',       component: resolve => require(['./views/nca/ordermanage/NCAGOrderDetailControl/NCAGOrderDetailControl.vue'], resolve) },
            { path: 'NCAOrderRequireControl',       component: resolve => require(['./views/nca/ordermanage/NCAOrderRequireControl.vue'], resolve) },
            { path: 'NCAMaterialInvoiceControl',    component: resolve => require(['./views/nca/ordermanage/NCAOrderDetailControl/NCAMaterialInvoiceControl.vue'], resolve) },
            { path: 'NCASOrderDetailControl',       component: resolve => require(['./views/nca/ordermanage/NCASOrderDetailControl/NCASOrderDetailControl.vue'], resolve) },
            { path: 'NCAHDOrderControl',            component: resolve => require(['./views/nca/ordermanage/NCAHDOrderControl/NCAHDOrderControl.vue'], resolve) },
            { path: 'NCAHDOrderDetailControl',      component: resolve => require(['./views/nca/ordermanage/NCAHDOrderControl/NCAHDOrderDetailControl.vue'], resolve) },
            { path: 'NCAReceivablesRuleControl',    component: resolve => require(['./views/nca/ordermanage/NCAReceivablesRuleControl.vue'], resolve) },
            { path: 'NCASaleOrderInstitutionsControl',    component: resolve => require(['./views/nca/ordermanage/NCASaleOrderInstitutionsControl'], resolve) },
            { path: 'NCASaleOrderControl',    component: resolve => require(['./views/nca/ordermanage/NCASaleOrderControl'], resolve) },
            { path: 'NCASaleOrderCompanyControl',    component: resolve => require(['./views/nca/ordermanage/NCASaleOrderCompanyControl'], resolve) },
            { path: 'NCAOrderReviewControl',    component: resolve => require(['./views/nca/ordermanage/NCAOrderReviewControl.vue'], resolve) },
            { path: 'NCAOrderReviewDetailControl',    component: resolve => require(['./views/nca/ordermanage/NCAOrderReviewDetailControl.vue'], resolve) },
            { path: 'NCADeliveryDetailControl',    component: resolve => require(['./views/nca/ordermanage/NCADeliveryDetailControl.vue'], resolve) }
    ]},
    { path: '/nca/baseconfig',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'NCAEstateControl',            component: resolve => require(['./views/nca/baseconfig/NCAEstateControl'], resolve) },
            { path: 'NCALandAgentEstateControl',   component: resolve => require(['./views/nca/baseconfig/NCALandAgentEstateControl'], resolve) },
            { path: 'NCAEstateDetailControl',      component: resolve => require(['./views/nca/baseconfig/NCAEstateDetailControl/NCAEstateDetailControl.vue'], resolve) },
            { path: 'NCARoomTypeDetailControl',    component: resolve => require(['./views/nca/baseconfig/NCARoomTypeDetailControl/NCARoomTypeDetailControl.vue'], resolve) },
            { path: 'NCAMaterielControl',          component: resolve => require(['./views/nca/baseconfig/NCAMaterielControl'], resolve) },
            { path: 'NCASupplierControl',          component: resolve => require(['./views/nca/baseconfig/NCASupplierControl'], resolve) },
            { path: 'NCASupplierTeamControl',      component: resolve => require(['./views/nca/baseconfig/NCASupplierTeamControl'], resolve) },
            { path: 'NCASupplierMaterielControl',  component: resolve => require(['./views/nca/baseconfig/NCASupplierMaterielControl'], resolve) },
            { path: 'NCASupplierProduceControl',  component: resolve => require(['./views/nca/baseconfig/NCASupplierProduceControl'], resolve) },
            { path: 'NCALandAgentControl',         component: resolve => require(['./views/nca/baseconfig/NCALandAgentControl'], resolve) },
            { path: 'NCALandAgentTeamControl',     component: resolve => require(['./views/nca/baseconfig/NCALandAgentTeamControl'], resolve) },
            { path: 'NCAForemanControl',           component: resolve => require(['./views/nca/baseconfig/NCAForemanControl'], resolve) },
            { path: 'NCAProduceControl',           component: resolve => require(['./views/nca/baseconfig/NCAProduceControl'], resolve) },
            { path: 'NCAProduceDetailControl',     component: resolve => require(['./views/nca/baseconfig/NCAProduceDetailControl'], resolve) },
            { path: 'NCAMaterielReviewDetailControl',          component: resolve => require(['./views/nca/baseconfig/NCAMaterielReviewDetailControl'], resolve) },
            { path: 'NCAMaterielSyncControl',          component: resolve => require(['./views/nca/baseconfig/NCAMaterielSyncControl'], resolve) },
            { path: 'NCATaskListControl',               component: resolve => require(['./views/nca/baseconfig/NCATaskListControl'], resolve) },
            { path: 'NCATaskDetailControl',             component: resolve => require(['./views/nca/baseconfig/NCATaskDetailControl'], resolve) },
            { path: 'NCATaskAllotControl',             component: resolve => require(['./views/nca/baseconfig/NCATaskAllotControl'], resolve) },
            { path: 'NCASiteConfigCaseControl',          component: resolve => require(['./views/nca/baseconfig/NCASiteConfigCaseControl'], resolve) },
            { path: 'NCASiteConfigDiaryControl',          component: resolve => require(['./views/nca/baseconfig/NCASiteConfigDiaryControl'], resolve) },
            { path: 'NCATaskAllotControl',             component: resolve => require(['./views/nca/baseconfig/NCATaskAllotControl'], resolve) },
            { path: 'NCAWorkerControl',           component: resolve => require(['./views/nca/baseconfig/NCAWorkerControl'], resolve) },
            { path: 'NCAWorkerBranchControl',           component: resolve => require(['./views/nca/baseconfig/NCAWorkerBranchControl'], resolve) },
            { path: 'NCAProjectControl',           component: resolve => require(['./views/nca/baseconfig/NCAProjectControl'], resolve) },
            { path: 'NCAProjectDetailControl',           component: resolve => require(['./views/nca/baseconfig/NCAProjectDetailControl'], resolve) },
            { path: 'NCAProjectDetailNewControl',           component: resolve => require(['./views/nca/baseconfig/NCAProjectDetailNewControl'], resolve) },
            { path: 'NCAProjectSpaceDetailControl',           component: resolve => require(['./views/nca/baseconfig/NCAProjectSpaceDetailControl'], resolve) },
            { path: 'NCAFinalAccountControl',           component: resolve => require(['./views/nca/baseconfig/NCAFinalAccountControl'], resolve) },
            { path: 'NCAFinalAccountDetailControl',           component: resolve => require(['./views/nca/baseconfig/NCAFinalAccountDetailControl'], resolve) },
            { path: 'NCAFinalAccountSpaceControl',           component: resolve => require(['./views/nca/baseconfig/NCAFinalAccountSpaceControl'], resolve) },
            { path: 'NCAWorkerPriceControl',           component: resolve => require(['./views/nca/baseconfig/NCAWorkerPriceControl'], resolve) },
            { path: 'NCANoticeControl',   component: resolve => require(['./views/nca/baseconfig/NCANoticeControl'], resolve) },
            { path: 'NCANoticeListControl',          component: resolve => require(['./views/nca/baseconfig/NCANoticeListControl'], resolve) },
            { path: 'NCANoticeDetailControl',          component: resolve => require(['./views/nca/baseconfig/NCANoticeDetailControl'], resolve) },
            { path: 'NCANoticeReceiveDetailControl',          component: resolve => require(['./views/nca/baseconfig/NCANoticeReceiveDetailControl'], resolve) },
            { path: 'NCAHumanResourceControl',   component: resolve => require(['./views/nca/baseconfig/NCAHumanResourceControl'], resolve) },
            { path: 'NCAHumanResourceDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCAHumanResourceDetailControl'], resolve) },
            { path: 'NCAAffiliatedCompanyControl',   component: resolve => require(['./views/nca/baseconfig/NCAAffiliatedCompanyControl'], resolve) },
            { path: 'NCABusinessCustomerControl',   component: resolve => require(['./views/nca/baseconfig/NCABusinessCustomerControl'], resolve) },
            { path: 'NCABusinessCustomerDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCABusinessCustomerDetailControl'], resolve) },
            { path: 'NCAEmployeeInformationControl',   component: resolve => require(['./views/nca/baseconfig/NCAEmployeeInformationControl'], resolve) },
            { path: 'NCAEmployeeDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCAEmployeeDetailControl'], resolve) },
            { path: 'NCASmallProgramControl',   component: resolve => require(['./views/nca/baseconfig/NCASmallProgramControl'], resolve) },
            { path: 'NCAReimburseRankControl',   component: resolve => require(['./views/nca/baseconfig/NCAReimburseRankControl'], resolve) },
            { path: 'NCABaseDataControl',   component: resolve => require(['./views/nca/baseconfig/NCABaseDataControl'], resolve) },
            { path: 'NCAMeetingManageControl',   component: resolve => require(['./views/nca/baseconfig/NCAMeetingManageControl'], resolve) },
            { path: 'NCAMeetingManageDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCAMeetingManageDetailControl'], resolve) },
            { path: 'NCAMeetingRoomControl',   component: resolve => require(['./views/nca/baseconfig/NCAMeetingRoomControl'], resolve) },
            { path: 'NCAMeetingRoomDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCAMeetingRoomDetailControl'], resolve) },
            { path: 'NCAMeetingMinuteControl',   component: resolve => require(['./views/nca/baseconfig/NCAMeetingMinuteControl'], resolve) },
            { path: 'NCAMeetingMinuteDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCAMeetingMinuteDetailControl'], resolve) },
            { path: 'NCAVehicleControl',   component: resolve => require(['./views/nca/baseconfig/NCAVehicleControl'], resolve) },
            { path: 'NCATransReceptionListControl',   component: resolve => require(['./views/nca/baseconfig/NCATransReceptionListControl'], resolve) },
            { path: 'NCATransReceptionDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCATransReceptionDetailControl'], resolve) },
            { path: 'NCATransReceptionListExpenseControl',   component: resolve => require(['./views/nca/baseconfig/NCATransReceptionListExpenseControl'], resolve) },
            { path: 'NCAAskForLeaveControl',   component: resolve => require(['./views/nca/baseconfig/NCAAskForLeaveControl'], resolve) },
            { path: 'NCAAskForLeaveDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCAAskForLeaveDetailControl'], resolve) },
            { path: 'NCAAskForLeaveTaskDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCAAskForLeaveTaskDetailControl'], resolve) },
            { path: 'NCATransReceptionExpenseDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCATransReceptionExpenseDetailControl'], resolve) },
            { path: 'NCADocumentManagementControl',   component: resolve => require(['./views/nca/baseconfig/NCADocumentManagementControl'], resolve) },
            { path: 'NCADocumentManagementDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCADocumentManagementDetailControl'], resolve) },
            { path: 'NCATestInDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCATestInDetailControl'], resolve) },
            { path: 'NCATestOutDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCATestOutDetailControl'], resolve) },
            { path: 'NCADocumentManagementTaskDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCADocumentManagementTaskDetailControl'], resolve) },
            { path: 'NCADocumentNoticeControl',   component: resolve => require(['./views/nca/baseconfig/NCADocumentNoticeControl'], resolve) },
            { path: 'NCADocumentNoticeDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCADocumentNoticeDetailControl'], resolve) },
            { path: 'NCATestNoticeControl',   component: resolve => require(['./views/nca/baseconfig/NCATestNoticeControl'], resolve) },
            { path: 'NCATestOutNoticeControl',   component: resolve => require(['./views/nca/baseconfig/NCATestOutNoticeControl'], resolve) },
            { path: 'NCATestTaskInDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCATestTaskInDetailControl'], resolve) },
            { path: 'NCATestTaskOutDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCATestTaskOutDetailControl'], resolve) },
            { path: 'NCASpecialExpenseControl',   component: resolve => require(['./views/nca/baseconfig/NCASpecialExpenseControl'], resolve) },
            { path: 'NCATransReceptionDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCATransReceptionDetailControl'], resolve) },
            { path: 'NCAContentManageControl',   component: resolve => require(['./views/nca/baseconfig/NCAContentManageControl'], resolve) },
            { path: 'NCAContentManageDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCAContentManageDetailControl'], resolve) },
            { path: 'NCAContentManageTypeControl',   component: resolve => require(['./views/nca/baseconfig/NCAContentManageTypeControl'], resolve) },
            { path: 'NCACorporateClientsControl',   component: resolve => require(['./views/nca/baseconfig/NCACorporateClientsControl'], resolve) },
            { path: 'NCACorporateClientsDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCACorporateClientsDetailControl'], resolve) },
            { path: 'NCADepartmentControl',   component: resolve => require(['./views/nca/baseconfig/NCADepartmentControl'], resolve) },
            { path: 'NCAUsergroupControl',   component: resolve => require(['./views/nca/baseconfig/NCAUsergroupControl'], resolve) },
            { path: 'NCACreditLineDetailtControl',   component: resolve => require(['./views/nca/baseconfig/NCACreditLineDetailtControl'], resolve) },
            { path: 'NCATestTaskAnswerInDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCATestTaskAnswerInDetailControl'], resolve) },
            { path: 'NCADocumentManagementNoticeTaskDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCADocumentManagementNoticeTaskDetailControl'], resolve) },
            { path: 'NCAProductSalesPriceControl',   component: resolve => require(['./views/nca/baseconfig/NCAProductSalesPriceControl'], resolve) },
            { path: 'NCAProductSalesPriceDetailControl',   component: resolve => require(['./views/nca/baseconfig/NCAProductSalesPriceDetailControl'], resolve) },
            { path: 'NCASystemDataInitializationControl',   component: resolve => require(['./views/nca/baseconfig/NCASystemDataInitializationControl'], resolve) },
            { path: 'NCAMessageListControl',   component: resolve => require(['./views/nca/baseconfig/NCAMessageListControl'], resolve) },
            { path: 'NCAProjectControlCopy',   component: resolve => require(['./views/nca/baseconfig/NCAProjectControlCopy'], resolve) },
            { path: 'NCAProjectDetailNewControlCopy',   component: resolve => require(['./views/nca/baseconfig/NCAProjectDetailNewControlCopy'], resolve) },
            { path: 'NCAPointTypeControl',   component: resolve => require(['./views/nca/baseconfig/NCAPointTypeControl'], resolve) }
        ]},


    { path: '/nca/purchasemanage',                   component: resolve => require(['./components/mainSystem'], resolve),
        children: [
          { path: 'NCAPurchaseControl',              component: resolve => require(['./views/nca/purchasemanage/NCAPurchaseControl.vue'], resolve) },
          { path: 'NCAPurchaseDetailControl',        component: resolve => require(['./views/nca/purchasemanage/NCAPurchaseDetailControl'], resolve) },
          { path: 'NCAPurchaseApplyDetailControl',   component: resolve => require(['./views/nca/purchasemanage/NCAPurchaseApplyDetailControl'], resolve) },
          { path: 'NCAPuchasePirntControl',          component: resolve => require(['./views/nca/purchasemanage/NCAPuchasePirntControl'], resolve) },
          { path: 'NCAPurchaseListControl',          component: resolve => require(['./views/nca/purchasemanage/NCAPurchaseListControl.vue'], resolve) },
          { path: 'NCAPuchaseApplyPirntControl',     component: resolve => require(['./views/nca/purchasemanage/NCAPuchaseApplyPirntControl'], resolve) },
          { path: 'NCAQualityAddControl',     component: resolve => require(['./views/nca/purchasemanage/NCAQualityAddControl'], resolve) },
          { path: 'NCAQualityAddDetailControl',     component: resolve => require(['./views/nca/purchasemanage/NCAQualityAddDetailControl'], resolve) },
          { path: 'NCAQualityCheckControl',     component: resolve => require(['./views/nca/purchasemanage/NCAQualityCheckControl'], resolve) },
          { path: 'NCAQualityCheckDetailControl',     component: resolve => require(['./views/nca/purchasemanage/NCAQualityCheckDetailControl'], resolve) },
          { path: 'NCAReturnNoteControl',     component: resolve => require(['./views/nca/purchasemanage/NCAReturnNoteControl'], resolve) },
          { path: 'NCAReturnNoteDetailControl',     component: resolve => require(['./views/nca/purchasemanage/NCAReturnNoteDetailControl'], resolve) }
    ]},

    { path: '/nca/productionmanage',                   component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'NCAMasterPlanControl',          component: resolve => require(['./views/nca/productionmanage/NCAMasterPlanControl'], resolve) },
            { path: 'NCAWeeklyPlanControl',          component: resolve => require(['./views/nca/productionmanage/NCAWeeklyPlanControl'], resolve) },
            { path: 'NCADailyPlanControl',           component: resolve => require(['./views/nca/productionmanage/NCADailyPlanControl'], resolve) },
            { path: 'NCAProductPlanControl',         component: resolve => require(['./views/nca/productionmanage/NCAProductPlanControl'], resolve) },
            { path: 'NCAProductPlanDetailControl',   component: resolve => require(['./views/nca/productionmanage/NCAProductPlanDetailControl'], resolve) },
            { path: 'NCAProductProcedureControl',    component: resolve => require(['./views/nca/productionmanage/NCAProductProcedureControl'], resolve) },
            { path: 'NCAProductPlanVerifyControl',   component: resolve => require(['./views/nca/productionmanage/NCAProductPlanVerifyControl'], resolve) },
            { path: 'NCAPlanVerifyListControl',      component: resolve => require(['./views/nca/productionmanage/NCAPlanVerifyListControl'], resolve) },
            { path: 'NCAPlanVerifyMaterielControl',  component: resolve => require(['./views/nca/productionmanage/NCAPlanVerifyMaterielControl'], resolve) },
            { path: 'NCAProductiveTaskControl',      component: resolve => require(['./views/nca/productionmanage/NCAProductiveTaskControl'], resolve) },
            { path: 'NCAProductiveTaskDetailControl',component: resolve => require(['./views/nca/productionmanage/NCAProductiveTaskDetailControl'], resolve) },
            { path: 'NCAProductTaskControl',      component: resolve => require(['./views/nca/productionmanage/NCAProductTaskControl'], resolve) },
            { path: 'NCAProductTaskDetailControl',      component: resolve => require(['./views/nca/productionmanage/NCAProductTaskDetailControl'], resolve) },
        ]},
      { path: '/nca/cashiermanage',                   component: resolve => require(['./components/mainSystem'], resolve),
          children: [
              { path: 'NCAGatheringControl',          component: resolve => require(['./views/nca/cashiermanage/NCAGatheringControl'], resolve) },
              { path: 'NCAGatheringTempControl',          component: resolve => require(['./views/nca/cashiermanage/NCAGatheringTempControl'], resolve) },
              { path: 'NCAPaymentConfirmControl',          component: resolve => require(['./views/nca/cashiermanage/NCAPaymentConfirmControl'], resolve) }
          ]},
    { path: '/nca/inventorymanage',                  component: resolve => require(['./components/mainSystem'], resolve),
      children: [
          { path: 'NCABuyInControl',                component: resolve => require(['./views/nca/inventorymanage/NCABuyInControl'], resolve) },
          { path: 'NCABuyInDetailControl',          component: resolve => require(['./views/nca/inventorymanage/NCABuyInDetailControl'], resolve) },
          { path: 'NCABuyInHistoryControl',         component: resolve => require(['./views/nca/inventorymanage/NCABuyInHistoryControl'], resolve) },
          { path: 'NCABuyInHistoryDetailControl',   component: resolve => require(['./views/nca/inventorymanage/NCABuyInHistoryDetailControl'], resolve) },
          { path: 'NCABuyInMaterielControl',        component: resolve => require(['./views/nca/inventorymanage/NCABuyInMaterielControl'], resolve) },
          { path: 'NCACheckInventoryControl',       component: resolve => require(['./views/nca/inventorymanage/NCACheckInventoryControl'], resolve) },
          { path: 'NCACheckInventoryDetailControl', component: resolve => require(['./views/nca/inventorymanage/NCACheckInventoryDetailControl'], resolve) },
          { path: 'NCAInventoryControl',            component: resolve => require(['./views/nca/inventorymanage/NCAInventoryControl'], resolve) },
          { path: 'NCAInventoryDetailControl',      component: resolve => require(['./views/nca/inventorymanage/NCAInventoryDetailControl'], resolve) },
          { path: 'NCAInventoryZoneDetailControl',  component: resolve => require(['./views/nca/inventorymanage/NCAInventoryZoneDetailControl'], resolve) },
          { path: 'NCASaleOutControl',              component: resolve => require(['./views/nca/inventorymanage/NCASaleOutControl'], resolve) },
          { path: 'NCASaleOutDetailControl',        component: resolve => require(['./views/nca/inventorymanage/NCASaleOutDetailControl'], resolve) },
          { path: 'NCASaleOutDetailControlOperate', component: resolve => require(['./views/nca/inventorymanage/NCASaleOutDetailControlOperate'], resolve) },
          { path: 'NCASaleOutHistoryControl',       component: resolve => require(['./views/nca/inventorymanage/NCASaleOutHistoryControl'], resolve) },
          { path: 'NCASaleOutHistoryDetailControl', component: resolve => require(['./views/nca/inventorymanage/NCASaleOutHistoryDetailControl'], resolve) },
          { path: 'NCASaleOutInvoiceControl',       component: resolve => require(['./views/nca/inventorymanage/NCASaleOutInvoiceControl'], resolve) },
          { path: 'NCAWarehouseControl',            component: resolve => require(['./views/nca/inventorymanage/NCAWarehouseControl'], resolve) },
          { path: 'NCAWarehouseDetailControl',      component: resolve => require(['./views/nca/inventorymanage/NCAWarehouseDetailControl'], resolve) },
          { path: 'NCAInvalidateControl',           component: resolve => require(['./views/nca/inventorymanage/NCAInvalidateControl'], resolve) },
          { path: 'NCAInvalidateApplyControl',           component: resolve => require(['./views/nca/inventorymanage/NCAInvalidateApplyControl'], resolve) },
          { path: 'NCAInvalidateApplyTaskControl',           component: resolve => require(['./views/nca/inventorymanage/NCAInvalidateApplyTaskControl'], resolve) },
          { path: 'NCABuyInMovingMaterielControl',        component: resolve => require(['./views/nca/inventorymanage/NCABuyInMovingMaterielControl'], resolve) },
          { path: 'NCAStockInApplyControl',        component: resolve => require(['./views/nca/inventorymanage/NCAStockInApplyControl'], resolve) },
          { path: 'NCAStockInApplyDetailControl',        component: resolve => require(['./views/nca/inventorymanage/NCAStockInApplyDetailControl'], resolve) },
          { path: 'NCAStockOutApplyControl',        component: resolve => require(['./views/nca/inventorymanage/NCAStockOutApplyControl'], resolve) },
          { path: 'NCAStockOutApplyDetailControl',        component: resolve => require(['./views/nca/inventorymanage/NCAStockOutApplyDetailControl'], resolve) },
          { path: 'NCAOtherInDetailControl',          component: resolve => require(['./views/nca/inventorymanage/NCAOtherInDetailControl'], resolve) },
          { path: 'NCAOtherOutDetailControl',          component: resolve => require(['./views/nca/inventorymanage/NCAOtherOutDetailControl'], resolve) },
          { path: 'NCAOtherInMaterielControl',          component: resolve => require(['./views/nca/inventorymanage/NCAOtherInMaterielControl'], resolve) },
          { path: 'NCAOtherInHistoryDetailControl',          component: resolve => require(['./views/nca/inventorymanage/NCAOtherInHistoryDetailControl'], resolve) },
          { path: 'NCAOtherOutDetailControlApply',          component: resolve => require(['./views/nca/inventorymanage/NCAOtherOutDetailControlApply'], resolve) },
          { path: 'NCAIdleApplyControl',              component: resolve => require(['./views/nca/inventorymanage/NCAIdleApplyControl'], resolve) },
          { path: 'NCAIdleApplyDetailControl',        component: resolve => require(['./views/nca/inventorymanage/NCAIdleApplyDetailControl'], resolve) },
          { path: 'NCAOtherOutHistoryDetailControl',          component: resolve => require(['./views/nca/inventorymanage/NCAOtherOutHistoryDetailControl.vue'], resolve) },
          { path: 'NCACollectGoodsControl',          component: resolve => require(['./views/nca/inventorymanage/NCACollectGoodsControl.vue'], resolve) },
          { path: 'NCACollectGoodsDetailControl',          component: resolve => require(['./views/nca/inventorymanage/NCACollectGoodsDetailControl.vue'], resolve) },
          { path: 'NCAReceiptListControl',          component: resolve => require(['./views/nca/inventorymanage/NCAReceiptListControl.vue'], resolve) },
          { path: 'NCAReceiptDetailControl',          component: resolve => require(['./views/nca/inventorymanage/NCAReceiptDetailControl.vue'], resolve) },
          { path: 'NCAProductInItemsControl',          component: resolve => require(['./views/nca/inventorymanage/NCAProductInItemsControl.vue'], resolve) },
          { path: 'NCAProductInSubmitControl',          component: resolve => require(['./views/nca/inventorymanage/NCAProductInSubmitControl.vue'], resolve) },
          { path: 'NCAProductOutItemsControl',          component: resolve => require(['./views/nca/inventorymanage/NCAProductOutItemsControl.vue'], resolve) },
          { path: 'NCAProductOutSubmitControl',          component: resolve => require(['./views/nca/inventorymanage/NCAProductOutSubmitControl.vue'], resolve) }
      ]},
    { path: '/nca/homepage',                        component: resolve => require(['./components/mainSystem'], resolve),
      children: [
        { path: 'NCAHomePageControl',               component: resolve => require(['./views/nca/homepage/NCAHomePageControl.vue'], resolve) },
    ]},
    { path: '/nca/longtermassets',                   component: resolve => require(['./components/mainSystem'], resolve),
      children: [
          { path: 'NCAFixedAssetsControl',              component: resolve => require(['./views/nca/longtermassets/NCAFixedAssetsControl'], resolve) },
          { path: 'NCAFixedAssetsRepairMaterials',              component: resolve => require(['./views/nca/longtermassets/NCAFixedAssetsRepairMaterials'], resolve) },
          { path: 'NCAAssetPurchaseDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetPurchaseDetailControl'], resolve) },
          { path: 'NCAAssetsAcceptanceDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetsAcceptanceDetailControl'], resolve) },
          { path: 'NCAAssetPurchaseTaskDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetPurchaseTaskDetailControl'], resolve) },
          { path: 'NCAAssetsAcceptanceTaskDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetsAcceptanceTaskDetailControl'], resolve) },
          { path: 'NCAConsumablesControl',           component: resolve => require(['./views/nca/longtermassets/NCAConsumablesControl'], resolve) },
          { path: 'NCAConsumablesDetailControl',           component: resolve => require(['./views/nca/longtermassets/NCAConsumablesDetailControl'], resolve) },
          { path: 'NCAAmortizeControl',   component: resolve => require(['./views/nca/longtermassets/NCAAmortizeControl'], resolve) },
          { path: 'NCAAmortizeDataControl',   component: resolve => require(['./views/nca/longtermassets/NCAAmortizeDataControl'], resolve) },
          { path: 'NCAAmortizeDetailControl',   component: resolve => require(['./views/nca/longtermassets/NCAAmortizeDetailControl'], resolve) },
          { path: 'NCAAmortizeReceiveControl',   component: resolve => require(['./views/nca/longtermassets/NCAAmortizeReceiveControl'], resolve) },
          { path: 'NCAAmortizeReceiveDetailControl',   component: resolve => require(['./views/nca/longtermassets/NCAAmortizeReceiveDetailControl'], resolve) },
          { path: 'NCAAmortizeConsumeControl',   component: resolve => require(['./views/nca/longtermassets/NCAAmortizeConsumeControl'], resolve) },
          { path: 'NCAAmortizeConsumeDetailControl',   component: resolve => require(['./views/nca/longtermassets/NCAAmortizeConsumeDetailControl'], resolve) },
          { path: 'NCAAssetRetirementControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetRetirementControl'], resolve) },
          { path: 'NCAFixedAssetsScrapDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAFixedAssetsScrapDetailControl'], resolve) },
          { path: 'NCADeferredAssetsScrapDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCADeferredAssetsScrapDetailControl'], resolve) },
          { path: 'NCAValueConsumablesScrapDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAValueConsumablesScrapDetailControl'], resolve) },
          { path: 'NCAFixedAssetsScrapTaskDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAFixedAssetsScrapTaskDetailControl'], resolve) },
          { path: 'NCAAssetInventoryControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetInventoryControl'], resolve) },
          { path: 'NCAAssetInventoryDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetInventoryDetailControl'], resolve) },
          { path: 'NCAAssetInventoryUsersDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetInventoryUsersDetailControl'], resolve) },
          { path: 'NCAAssetInventoryTaskDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetInventoryTaskDetailControl'], resolve) },
          { path: 'NCAAssetInventoryUsersTaskDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetInventoryUsersTaskDetailControl'], resolve) },
          { path: 'NCAAmortizeControlCopy',              component: resolve => require(['./views/nca/longtermassets/NCAAmortizeControlCopy'], resolve) },
          { path: 'NCAAmortizeDetailControlCopy',              component: resolve => require(['./views/nca/longtermassets/NCAAmortizeDetailControlCopy'], resolve) },
          { path: 'NCAAmortizeScribeOrderControl',              component: resolve => require(['./views/nca/longtermassets/NCAAmortizeScribeOrderControl'], resolve) },
          { path: 'NCAAmortizeScribeOrderDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAmortizeScribeOrderDetailControl'], resolve) },
          { path: 'NCAAmortizePurchaseOrderControl',              component: resolve => require(['./views/nca/longtermassets/NCAAmortizePurchaseOrderControl'], resolve) },
          { path: 'NCAAmortizePurchaseOrderDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAmortizePurchaseOrderDetailControl'], resolve) },
          { path: 'NCAAssetRetirementDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCAAssetRetirementDetailControl'], resolve) },
          { path: 'NCADevelopControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopControl'], resolve) },
          { path: 'NCADevelopControlCopy',              component: resolve => require(['./views/nca/longtermassets/NCADevelopControlCopy'], resolve) },
          { path: 'NCADevelopDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopDetailControl'], resolve) },
          { path: 'NCADevelopDetailControlCopy',              component: resolve => require(['./views/nca/longtermassets/NCADevelopDetailControlCopy'], resolve) },
          { path: 'NCAAmortizeScribeOrderDetailControlCopy',              component: resolve => require(['./views/nca/longtermassets/NCAAmortizeScribeOrderDetailControlCopy'], resolve) },
          { path: 'NCADevelopScribeOrderDetailControlCopy',              component: resolve => require(['./views/nca/longtermassets/NCADevelopScribeOrderDetailControlCopy'], resolve) },
          { path: 'NCADevelopScribeOrderControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopScribeOrderControl'], resolve) },
          { path: 'NCADevelopScribeOrderDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopScribeOrderDetailControl'], resolve) },
          { path: 'NCADevelopReceiveControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopReceiveControl'], resolve) },
          { path: 'NCADevelopReceiveDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopReceiveDetailControl'], resolve) },
          { path: 'NCADevelopPurchaseOrderControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopPurchaseOrderControl'], resolve) },
          { path: 'NCADevelopPurchaseOrderDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopPurchaseOrderDetailControl'], resolve) },
          { path: 'NCADevelopConsumeControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopConsumeControl'], resolve) },
          { path: 'NCADevelopConsumeDetailControl',              component: resolve => require(['./views/nca/longtermassets/NCADevelopConsumeDetailControl'], resolve) },
          // { path: 'NCAAmortizeConsumeControlCopy',              component: resolve => require(['./views/nca/longtermassets/NCAAmortizeConsumeControlCopy'], resolve) },
      ]},
    { path: '/system',          component: resolve => require(['./components/mainSystem'], resolve),
      children: [
        { path: 'home',                   component: resolve => require(['./views/home'], resolve) },
    ]},
    { path: '/example',           component: resolve => require(['./components/mainSystem'], resolve),
      children: [
        { path: 'example',   component: resolve => require(['./views/example/example'], resolve) },
    ]}
  ]
})
